version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: hrms_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
    networks:
      - hrms_network

  backend:
    build: .
    container_name: hrms_backend
    restart: always
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      PORT: 7000
      MONGO_URI: mongodb://$${MONGO_USER}:$${MONGO_PASS}@mongodb:27017/admin?authSource=admin
    networks:
      - hrms_network

volumes:
  mongo_data:

networks:
  hrms_network:
    driver: bridge
